# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{solve360}
  s.version = "0.0.9"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Stephen Bartholomew"]
  s.date = %q{2010-06-18}
  s.description = %q{}
  s.email = %q{Stephen Bartholomew}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "NOTES",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "lib/solve360.rb",
     "lib/solve360/company.rb",
     "lib/solve360/config.rb",
     "lib/solve360/contact.rb",
     "lib/solve360/item.rb",
     "spec/api_settings.yml",
     "spec/api_settings.yml.sample",
     "spec/fixtures/contacts/create-success.json",
     "spec/fixtures/contacts/find-all.json",
     "spec/fixtures/contacts/find-company-success.json",
     "spec/fixtures/contacts/find-success.json",
     "spec/fixtures/contacts/index.json",
     "spec/fixtures/contacts/save-failed.json",
     "spec/fixtures/contacts/show-success.json",
     "spec/fixtures/contacts/update-success.json",
     "spec/solve360/item_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/curve21/solve360}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Libary for working with the Solve360 CRM API}
  s.test_files = [
    "spec/solve360/item_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<configify>, [">= 0.0.1"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_runtime_dependency(%q<httparty>, [">= 0.4.5"])
    else
      s.add_dependency(%q<configify>, [">= 0.0.1"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<httparty>, [">= 0.4.5"])
    end
  else
    s.add_dependency(%q<configify>, [">= 0.0.1"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<httparty>, [">= 0.4.5"])
  end
end

