#!/usr/bin/env ruby
puts "Loading Solve360 gem"

libs =  " -r irb/completion"
libs << " -r rubygems "
libs <<  " -r #{File.dirname(__FILE__) + '/../lib/solve360.rb'}"
libs << " -r #{File.dirname(__FILE__) + '/console-startup.rb'}"

if ARGV[0] && ARGV[0].match(/\.rb/)
  puts "Loading configuration #{ARGV[0]}"
  libs << " -r #{ARGV[0]}"
end

exec "irb #{libs} --simple-prompt"